
name: Build and dockerize the Survival API

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
    
jobs:
  build-model:
    name: >-
      Train and build the wheel file for the survival model
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for the survival model
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
    
      - name: Train the survival model and create the pkl file
        run: |
          python survival_model/train_pipeline.py

      - name: Generate wheel file
        run: |
          pip install --upgrade build
          python -m build

      - name: Upload wheel file
        uses: actions/upload-artifact@v4
        with:
            name: release-dists
            path: dist/
  

  build-api:
    name: >-
      Build the Docker image and push it to the Docker registry
    needs:
    - build-model
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Set the model version as an environment variable
        if: false
        id: set-version
        run: |
          VER=$(cat ./survival_model/VERSION)
          echo "VERSION=$VER" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
            context: ./survival_api
            file: ./survival_api/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/patient-survival-app:latest